import { NextRequest, NextResponse } from 'next/server'
import { createServerSupabaseClient, createAdminClient } from '@/lib/supabase/server'

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const reportId = searchParams.get('id')
  const format = searchParams.get('format') || 'pdf'

  if (!reportId) return NextResponse.json({ error: 'Report ID required' }, { status: 400 })

  const supabase = await createServerSupabaseClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const adminClient = createAdminClient()
  const { data: report } = await adminClient
    .from('reports')
    .select('*')
    .eq('id', reportId)
    .eq('user_id', user.id)
    .single()

  if (!report) return NextResponse.json({ error: 'Report not found' }, { status: 404 })

  const content = (report.content as Record<string, unknown>)?.text as string || ''

  if (format === 'pdf') {
    // Generate HTML for PDF
    const html = generateReportHTML(report.title, content)
    const htmlBytes = new TextEncoder().encode(html)

    return new NextResponse(htmlBytes, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `attachment; filename="${report.title.replace(/[^a-z0-9]/gi, '_')}.html"`,
        'X-Note': 'Open in browser and use Print > Save as PDF for best results',
      },
    })
  }

  if (format === 'ppt') {
    // Generate a simple PowerPoint-compatible HTML
    const pptHtml = generatePresentationHTML(report.title, content)
    const bytes = new TextEncoder().encode(pptHtml)

    return new NextResponse(bytes, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `attachment; filename="${report.title.replace(/[^a-z0-9]/gi, '_')}_presentation.html"`,
      },
    })
  }

  return NextResponse.json({ error: 'Invalid format' }, { status: 400 })
}

function generateReportHTML(title: string, content: string): string {
  // Convert markdown-like content to HTML
  const htmlContent = content
    .split('\n')
    .map(line => {
      if (line.startsWith('# ')) return `<h1>${line.slice(2)}</h1>`
      if (line.startsWith('## ')) return `<h2>${line.slice(3)}</h2>`
      if (line.startsWith('### ')) return `<h3>${line.slice(4)}</h3>`
      if (line.startsWith('- ')) return `<li>${line.slice(2)}</li>`
      if (line.startsWith('**') && line.endsWith('**')) return `<strong>${line.slice(2, -2)}</strong>`
      if (line.trim() === '') return '<br>'
      return `<p>${line}</p>`
    })
    .join('\n')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', -apple-system, sans-serif; color: #1a1a1a; background: white; }
    .page { max-width: 800px; margin: 0 auto; padding: 60px 48px; }
    .header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 48px; padding-bottom: 24px; border-bottom: 2px solid #6366f1; }
    .logo { display: flex; align-items: center; gap: 8px; }
    .logo-icon { width: 32px; height: 32px; background: linear-gradient(135deg, #6366f1, #4f46e5); border-radius: 8px; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold; font-size: 14px; }
    .logo-text { font-weight: 700; font-size: 18px; color: #1a1a1a; }
    .report-meta { text-align: right; font-size: 12px; color: #6b7280; }
    .report-title { font-size: 28px; font-weight: 800; color: #1a1a1a; margin-bottom: 8px; }
    .generated { font-size: 12px; color: #9ca3af; margin-bottom: 48px; }
    h1 { font-size: 24px; font-weight: 700; color: #6366f1; margin: 32px 0 12px; }
    h2 { font-size: 18px; font-weight: 600; color: #374151; margin: 24px 0 10px; }
    h3 { font-size: 15px; font-weight: 600; color: #4b5563; margin: 16px 0 8px; }
    p { font-size: 14px; line-height: 1.7; color: #4b5563; margin: 6px 0; }
    li { font-size: 14px; line-height: 1.7; color: #4b5563; margin-left: 20px; margin-bottom: 4px; }
    strong { color: #1a1a1a; }
    .footer { margin-top: 64px; padding-top: 24px; border-top: 1px solid #e5e7eb; text-align: center; font-size: 11px; color: #9ca3af; }
    @media print {
      .page { padding: 40px; }
      @page { margin: 1cm; }
    }
  </style>
</head>
<body>
  <div class="page">
    <div class="header">
      <div class="logo">
        <div class="logo-icon">A</div>
        <div class="logo-text">AdPilot AI</div>
      </div>
      <div class="report-meta">
        Generated by AdPilot AI<br>
        ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
      </div>
    </div>
    <div class="report-title">${title}</div>
    <div class="generated">AI-Generated Performance Marketing Report</div>
    ${htmlContent}
    <div class="footer">
      Generated by AdPilot AI — AI-Powered Performance Marketing Manager<br>
      Confidential · For internal use only
    </div>
  </div>
</body>
</html>`
}

function generatePresentationHTML(title: string, content: string): string {
  const slides = content.split('\n# ').filter(Boolean)

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', -apple-system, sans-serif; background: #0f0f23; }
    .slide { width: 1280px; min-height: 720px; margin: 20px auto; background: white; border-radius: 16px; overflow: hidden; display: flex; flex-direction: column; position: relative; }
    .slide-header { background: linear-gradient(135deg, #6366f1, #4338ca); color: white; padding: 48px 64px 32px; }
    .slide-number { font-size: 12px; opacity: 0.6; margin-bottom: 8px; }
    .slide-title { font-size: 36px; font-weight: 800; }
    .slide-body { padding: 40px 64px; flex: 1; }
    .slide-body p, .slide-body li { font-size: 18px; line-height: 1.8; color: #374151; margin-bottom: 12px; }
    .slide-body li { margin-left: 24px; }
    .slide-footer { padding: 20px 64px; background: #f9fafb; border-top: 1px solid #e5e7eb; display: flex; justify-content: space-between; align-items: center; }
    .slide-footer span { font-size: 12px; color: #9ca3af; }
    .title-slide .slide-header { min-height: 720px; display: flex; flex-direction: column; justify-content: center; }
    .title-slide .slide-header .slide-title { font-size: 56px; }
  </style>
</head>
<body>
  <div class="slide title-slide">
    <div class="slide-header">
      <div class="slide-number">SLIDE 1</div>
      <div class="slide-title">${title}</div>
      <p style="opacity:0.8; margin-top:16px; font-size:18px;">Generated by AdPilot AI · ${new Date().toLocaleDateString()}</p>
    </div>
  </div>
  ${slides.slice(0, 10).map((slide, i) => {
    const lines = slide.split('\n').filter(Boolean)
    const slideTitle = lines[0] || `Slide ${i + 2}`
    const slideContent = lines.slice(1).map(line => {
      if (line.startsWith('## ')) return `<h3 style="font-size:22px;font-weight:600;color:#374151;margin-bottom:10px">${line.slice(3)}</h3>`
      if (line.startsWith('- ')) return `<li>${line.slice(2)}</li>`
      if (line.trim()) return `<p>${line}</p>`
      return ''
    }).join('\n')

    return `
  <div class="slide">
    <div class="slide-header">
      <div class="slide-number">SLIDE ${i + 2}</div>
      <div class="slide-title">${slideTitle}</div>
    </div>
    <div class="slide-body">${slideContent}</div>
    <div class="slide-footer">
      <span>AdPilot AI</span>
      <span>${i + 2} / ${Math.min(slides.length + 1, 11)}</span>
    </div>
  </div>`
  }).join('\n')}
</body>
</html>`
}
